# Содержание
- [Numpy](#numpy)
    - [Создание массивов](#arr)
    - [Операции на массивах](#ops)
    - [Работа с пропущенными значениями](#nans)
    - [Индексация и поиск в массивах](#index)
    - [Объединение массивов](#join)
    - [Поиск внутри массивов](#search)
    - [Обработка элементов по условию](#conds)
    - [Cортировка массивов](#sort)
    - [Сравнение массивов](#compar)
    - [Математические операции](#math)
    - [Функции линейной алгебры](#linalg)


 <a name='numpy'></a>
# Numpy

 <a name='1.1'></a>
## Описание

NumPy - это библиотека для языка программирования Python, которая предоставляет мощные инструменты для работы с массивами и матрицами данных. Она включает в себя функции для работы с линейной алгеброй, случайными числами, преобразованиями Фурье и многими другими математическими операциями.

Основным компонентом NumPy является объект массива numpy.ndarray, который представляет собой многомерный массив элементов одного типа данных. Эти массивы могут иметь разные размерности и формы, и могут быть использованы для выполнения быстрых математических операций на больших объемах данных.

NumPy также предоставляет множество функций для работы с массивами, таких как сортировка, индексация, решение уравнений, операции с логическими значениями и т.д. Библиотека также имеет множество инструментов для визуализации данных, в том числе инструменты для построения графиков и диаграмм.

NumPy является ключевой библиотекой для научных вычислений и анализа данных на Python, и широко используется в областях, таких как машинное обучение, обработка изображений, обработка звука и многих других.

Объект ndarray (N-dimensional array) в библиотеке NumPy представляет собой многомерный массив элементов одного типа данных, в то время как обычный list в Python может содержать элементы разных типов и не имеет поддержки для многомерных массивов.

Вот несколько отличий между ndarray и list:

1. ndarray может иметь фиксированные размеры и формы (т.е. количество элементов в каждом измерении), в то время как list может иметь произвольную длину и может содержать элементы разных типов.

2. ndarray обеспечивает быстрый доступ к элементам массива, в то время как для доступа к элементам списка требуется выполнение поиска элемента по индексу.

3. ndarray имеет поддержку для операций линейной алгебры и других математических операций над многомерными массивами, что делает его полезным для выполнения научных и инженерных вычислений. В то время как списки могут быть использованы для хранения и манипулирования данными различных типов, но они не предоставляют такой же функциональности для выполнения математических операций.

4. ndarray обычно занимает меньше памяти, чем list, особенно если массив содержит большое количество элементов, т.к. все элементы ndarray имеют одинаковый тип данных и могут быть хранены в памяти более эффективно.

В целом, ndarray является более эффективным и удобным инструментом для работы с многомерными массивами и выполнения научных вычислений, в то время как list может быть полезен для хранения и манипулирования данными различных типов и длин.

In [1]:
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version

 <a name='arr'></a>
Создание массивов

In [2]:
# Создание массива ndarray из списка
arr = np.array([1, 2, 3, 4, 5])
print(arr) # [1 2 3 4 5]
print(type(arr)) # <class 'numpy.ndarray'>

# Создание списка
lst = [1, 2, 3, 4, 5]
print(lst) # [1, 2, 3, 4, 5]
print(type(lst)) # <class 'list'>

# Доступ к элементам массива
print(arr[0]) # 1

# Доступ к элементам списка
print(lst[0]) # 1

# Изменение элемента массива
arr[0] = 0
print(arr) # [0 2 3 4 5]

# Изменение элемента списка
lst[0] = 0
print(lst) # [0, 2, 3, 4, 5]

# Сложение элементов массива
print(arr + arr) # [0 4 6 8 10]

# Сложение элементов списка
print(lst + lst) # [0, 2, 3, 4, 5, 0, 2, 3, 4, 5]

# Умножение элементов массива
print(arr * 2) # [ 0  4  6  8 10]

# Умножение элементов списка
print(lst * 2) # [0, 2, 3, 4, 5, 0, 2, 3, 4, 5]

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
<class 'list'>
1
1
[0 2 3 4 5]
[0, 2, 3, 4, 5]
[ 0  4  6  8 10]
[0, 2, 3, 4, 5, 0, 2, 3, 4, 5]
[ 0  4  6  8 10]
[0, 2, 3, 4, 5, 0, 2, 3, 4, 5]


In [3]:
# Создание двумерного массива
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Создание двумерного массива:\n", arr)

# Получение формы массива
shape = arr.shape
print("Получение формы массива:\n", shape)  # (2, 3)

# Получение количества измерений
ndim = arr.ndim
print("Получение количества измерений:\n", ndim)  # 2

# Получение общего количества элементов
size = arr.size
print("Получение общего количества элементов:\n", size)  # 6

# Получение типа данных элементов массива
dtype = arr.dtype
print("Получение типа данных элементов массива:\n", dtype) # int64

Создание двумерного массива:
 [[1 2 3]
 [4 5 6]]
Получение формы массива:
 (2, 3)
Получение количества измерений:
 2
Получение общего количества элементов:
 6
Получение типа данных элементов массива:
 int64


In [4]:
# Создание трехмерного массива
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Создание трехмерного массива:\n", arr_3d)

# Получение формы массива
shape = arr_3d.shape
print("Получение формы массива:\n", shape)  # (2, 2, 2)

# Получение количества измерений
ndim = arr_3d.ndim
print("Получение количества измерений:\n", ndim)  # 3

# Получение общего количества элементов
size = arr_3d.size
print("Получение общего количества элементов:\n", size)  # 8

# Получение типа данных элементов массива
dtype = arr_3d.dtype
print("Получение типа данных элементов массива:\n", dtype) # int64

Создание трехмерного массива:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Получение формы массива:
 (2, 2, 2)
Получение количества измерений:
 3
Получение общего количества элементов:
 8
Получение типа данных элементов массива:
 int64


In [5]:
# Создание массива из 10 нулей
print("Массив нулей:\n", np.zeros(10))

# Создание массива из 10 единиц
print("Массив единиц:\n", np.ones(10))

Массив нулей:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Массив единиц:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
# Повторение числа 10 пять раз в массиве
print("Повторение числа 10 пять раз в массиве:\n", np.repeat(10,5))

# Повторение каждого элемента в массиве 'a' три раза
a= np.array([10,20,30])
print("Повторение каждого элемента в массиве 'a' три раза:\n", np.repeat(a,3))

# Создание массива из числа 10
print("Массив из числа 10:\n", np.full(5,10))

Повторение числа 10 пять раз в массиве:
 [10 10 10 10 10]
Повторение каждого элемента в массиве 'a' три раза:
 [10 10 10 20 20 20 30 30 30]
Массив из числа 10:
 [10 10 10 10 10]


In [7]:
# Создание массива нечетных чисел от 1 до 19
ar1 = np.arange(1,20)
print("Массив нечетных чисел:\n", ar1[ar1%2 ==1])

# Создание массива четных чисел от 2 до 20
ar1 = np.arange(1,20)
print("Массив четных чисел:\n", ar1[ar1%2 == 0])

# Генерация четырех равномерно распределенных чисел в диапазоне от 10 до 20
print("Генерация четырех равномерно распределенных чисел в диапазоне от 10 до 20:\n", np.linspace(10,20,4))

# Генерация одиннадцати равномерно распределенных чисел в диапазоне от 10 до 20
print("Генерация одиннадцати равномерно распределенных чисел в диапазоне от 10 до 20:\n", np.linspace(10,20,11))

Массив нечетных чисел:
 [ 1  3  5  7  9 11 13 15 17 19]
Массив четных чисел:
 [ 2  4  6  8 10 12 14 16 18]
Генерация четырех равномерно распределенных чисел в диапазоне от 10 до 20:
 [10.         13.33333333 16.66666667 20.        ]
Генерация одиннадцати равномерно распределенных чисел в диапазоне от 10 до 20:
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [8]:
# Создание массива из четырех случайных значений
print("Массив случайных значений:\n", np.random.random(4))

# Генерация массива из пяти случайных целых чисел в диапазоне от 0 до 499
print("Генерация массива из пяти случайных целых чисел в диапазоне от 0 до 499:\n", np.random.randint(0,500,5))

# Генерация массива из десяти случайных целых чисел в диапазоне от 0 до 499
print("Генерация массива из десяти случайных целых чисел в диапазоне от 0 до 499:\n", np.random.randint(0,500,10))

Массив случайных значений:
 [0.95037172 0.34982612 0.67549068 0.51558057]
Генерация массива из пяти случайных целых чисел в диапазоне от 0 до 499:
 [361 403 266 365 130]
Генерация массива из десяти случайных целых чисел в диапазоне от 0 до 499:
 [124  88 170 150  23 268 481 158 252 338]


In [9]:
# С помощью random.seed можно генерировать один и тот же массив случайных чисел
np.random.seed(0)
print("Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:\n", np.random.randint(0,100,10))
np.random.seed(0)
print("Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:\n", np.random.randint(0,100,10))

np.random.seed(1)
print("Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:\n", np.random.randint(0,100,10))
np.random.seed(1)
print("Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:\n", np.random.randint(0,100,10))
# Повторение той же команды без перезадания seed даст другой результат
print("Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:\n", np.random.randint(0,100,10))

Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:
 [44 47 64 67 67  9 83 21 36 87]
Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:
 [44 47 64 67 67  9 83 21 36 87]
Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:
 [37 12 72  9 75  5 79 64 16  1]
Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:
 [37 12 72  9 75  5 79 64 16  1]
Генерация массива случайных целых чисел от 0 до 99 с помощью random.seed:
 [76 71  6 25 50 20 18 84 11 28]


In [10]:
# Создание массива случайных чисел с плавающей запятой
print("Генерация массива случайных чисел с плавающей запятой от 5 до 10 с помощью random.uniform:\n", np.random.uniform(5,10, size=(10)))

# Нормальное распределение (среднее значение=0 и дисперсия=1)
print("\nНормальное распределение:", np.random.randn(10))

Генерация массива случайных чисел с плавающей запятой от 5 до 10 с помощью random.uniform:
 [5.13693797 8.35233755 7.08652401 7.79344914 5.70193469 5.99050745
 9.00372284 9.84130788 6.56712089 8.46161308]

Нормальное распределение: [-0.17242821 -0.87785842  0.04221375  0.58281521 -1.10061918  1.14472371
  0.90159072  0.50249434  0.90085595 -0.68372786]


In [11]:
# Создание массива целых чисел от 1 до 5
a = np.arange(1,6)
print("Исходный массив a: ")
print(a)

print("Случайный выбор 3 элементов из массива с повторениями: ")
with_replacement = np.random.choice(a, size=3, replace=True)
print(with_replacement)

print("Случайный выбор 3 элементов из массива без повторений: ")
without_replacement = np.random.choice(a, size=3, replace=False)
print(without_replacement)

Исходный массив a: 
[1 2 3 4 5]
Случайный выбор 3 элементов из массива с повторениями: 
[3 2 1]
Случайный выбор 3 элементов из массива без повторений: 
[1 5 3]


 <a name='ops'></a>
Операции на массивах

In [12]:
# Извлечение целой части
print("Целая часть:", np.floor(np.random.uniform(5,10, size=(10))))

# Отбрасывание десятичной части
print("\nОтбрасывание десятичной части:", np.trunc(np.random.uniform(5,10, size=(10))))

# Преобразование массива с плавающей запятой в массив целых чисел
print("\nПреобразование массива:", np.random.uniform(5,10, size=(10)).astype(int))

Целая часть: [5. 7. 5. 9. 9. 6. 7. 7. 8. 9.]

Отбрасывание десятичной части: [6. 6. 7. 9. 7. 7. 8. 5. 5. 8.]

Преобразование массива: [5 9 7 7 9 6 7 8 6 7]


In [13]:
# Перечисление элементов Numpy массивов
print("\nПеречисление элементов массива:")
for index, value in enumerate(np.random.randn(10)):
    print(index, value)


Перечисление элементов массива:
0 -0.8948252289681984
1 0.3300628215380945
2 1.0485909989931987
3 1.3498993497991543
4 1.2456751071425367
5 -0.6911914720960863
6 1.281073378393483
7 -0.7270643100637517
8 -0.7991686943680119
9 -0.003545621848406033


In [14]:
arr2 = np.arange(1,20)
print("Массив arr2:")
print(arr2)

# Сумма всех элементов в массиве
print("Сумма всех элементов в массиве arr2:")
print(arr2.sum())

# Кумулятивная сумма элементов массива
print("Кумулятивная сумма элементов массива arr2:")
print(np.cumsum(arr2))

Массив arr2:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Сумма всех элементов в массиве arr2:
190
Кумулятивная сумма элементов массива arr2:
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190]


In [15]:
# Поиск минимального числа в массиве
print("Минимальное число в массиве arr2:")
print(arr2.min())

# Поиск максимального числа в массиве
print("Максимальное число в массиве arr2:")
print(arr2.max())

# Поиск индекса минимального числа в массиве
print("Индекс минимального числа в массиве arr2:")
print(arr2.argmin())

# Поиск индекса максимального числа в массиве
print("Индекс максимального числа в массиве arr2:")
print(arr2.argmax())

Минимальное число в массиве arr2:
1
Максимальное число в массиве arr2:
19
Индекс минимального числа в массиве arr2:
0
Индекс максимального числа в массиве arr2:
18


In [16]:
# Поиск среднего значения всех чисел в массиве
print("Среднее значение всех чисел в массиве arr2:")
print(arr2.mean())

# Поиск медианы всех чисел в массиве arr2
print("Медиана всех чисел в массиве arr2:")
print(np.median(arr2))

# Дисперсия
print("Дисперсия массива arr2:")
print(np.var(arr2))

# Стандартное отклонение
print("Стандартное отклонение массива arr2:")
print(np.std(arr2))

# Рассчет процентилей
print("70-й процентиль массива arr2:")
print(np.percentile(arr2,70))

# Рассчет 10-го и 70-го процентилей
print("10-й и 70-й процентили массива arr2:")
print(np.percentile(arr2,[10,70]))

Среднее значение всех чисел в массиве arr2:
10.0
Медиана всех чисел в массиве arr2:
10.0
Дисперсия массива arr2:
30.0
Стандартное отклонение массива arr2:
5.477225575051661
70-й процентиль массива arr2:
13.6
10-й и 70-й процентили массива arr2:
[ 2.8 13.6]


In [17]:
A = np.array([[1,2,3,4] , [5,6,7,8] , [10 , 11 , 25 ,3] , [14,15,16,33]])
print(A)
# Сумма всех чисел в 2D массиве
print("Сумма всех чисел в 2D массиве:", A.sum())
# Максимальное число в 2D массиве
print("Максимальное число в 2D массиве:", A.max())
# Минимальное число в 2D массиве
print("Минимальное число в 2D массиве:", A.min())
# Минимальное значение в столбцах
print("Минимальное значение в столбцах:", np.amin(A, axis=0))
# Минимальное значение в строках
print("Минимальное значение в строках:", np.amin(A, axis=1))
# Среднее значение всех чисел в 2D массиве
print("Среднее значение всех чисел в 2D массиве:", A.mean())
# Среднее значение
print("Среднее значение:", np.mean(A))
# Медиана
print("Медиана:", np.median(A))
# 50-й процентиль = Медиана
print("50-й процентиль = Медиана:", np.percentile(A,50))
# Дисперсия
print("Дисперсия:", np.var(A))
# Стандартное отклонение
print("Стандартное отклонение:", np.std(A))
# Расчет перцентилей
print("75-й процентиль:", np.percentile(A,75))
# Расчет 10-го и 70-го процентилей
print("25-й и 75-й процентили:", np.percentile(A,[25,75]))
# Перечисление элементов Numpy 2D массива
print("Перечисление элементов Numpy 2D массива с помощью np.ndenumerate():")
for index, value in np.ndenumerate(A):
    print(index, value)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 25  3]
 [14 15 16 33]]
Сумма всех чисел в 2D массиве: 163
Максимальное число в 2D массиве: 33
Минимальное число в 2D массиве: 1
Минимальное значение в столбцах: [1 2 3 3]
Минимальное значение в строках: [ 1  5  3 14]
Среднее значение всех чисел в 2D массиве: 10.1875
Среднее значение: 10.1875
Медиана: 7.5
50-й процентиль = Медиана: 7.5
Дисперсия: 72.77734375
Стандартное отклонение: 8.53096382303899
75-й процентиль: 14.25
25-й и 75-й процентили: [ 3.75 14.25]
Перечисление элементов Numpy 2D массива с помощью np.ndenumerate():
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 10
(2, 1) 11
(2, 2) 25
(2, 3) 3
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 33


 <a name='index'></a>
Индексация и поиск в массивах

In [18]:
# Чтение элементов массива
a = np.array([9,5,1,3,6,2])
# Получение первого элемента массива
print("Получение первого элемента массива", a[0])
# Получение всех элементов массива, кроме первого
print("Получение всех элементов массива, кроме первого", a[1:])
# Получение 2-го, 3-го и 4-го значения из массива
print("Получение 2-го, 3-го и 4-го значения из массива", a[1:4])
# Получение последнего элемента массива
print("Получение последнего элемента массива", a[-1])
# Получение 3-го с конца элемента массива
print("Получение 3-го с конца элемента массива", a[-3])
# Получение среза массива от 3-го до последнего
print("Получение среза массива от 3-го до последнего", a[-3:-1])
# Замена элементов в массиве
ar = np.arange(1,20)
# Замена четных чисел на 0
rep1 = np.where(ar % 2 == 0, 0 , ar)
print("Замена четных чисел на 0", rep1)
ar2 = np.array([10, 20 , 30 , 10 ,10 ,20, 20])
# Замена числа 10 на 99
rep2 = np.where(ar2 == 10, 99 , ar2)
print("Замена числа 10 на 99", rep2)
p2 = np.arange(0,100,10)
# Замена значений с индексом 0, 3, 5 на 33, 55, 99
np.put(p2, [0, 3 , 5], [33, 55, 99])
print("Замена значений с индексом 0, 3, 5 на 33, 55, 99", p2)

Получение первого элемента массива 9
Получение всех элементов массива, кроме первого [5 1 3 6 2]
Получение 2-го, 3-го и 4-го значения из массива [5 1 3]
Получение последнего элемента массива 2
Получение 3-го с конца элемента массива 3
Получение среза массива от 3-го до последнего [3 6]
Замена четных чисел на 0 [ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]
Замена числа 10 на 99 [99 20 30 99 99 20 20]
Замена значений с индексом 0, 3, 5 на 33, 55, 99 [33 10 20 55 40 99 60 70 80 90]


 <a name='nans'></a>
Работа с пропущенными значениями

In [19]:
# Пропущенные значения в массиве
a = np.array([3 ,np.nan,9,5,7,np.nan,11,np.inf])
print("Пропущенные значения в массиве",a)

# Поиск пропущенных значений и возврат их в виде булевого массива
print("Поиск пропущенных значений и возврат их в виде булевого массива",np.isnan(a))

# Индекс пропущенных значений в массиве
print("Индекс пропущенных значений в массиве",np.where(np.isnan(a)))

# Замена всех пропущенных значений на 100
a[np.isnan(a)] = 100
print("Замена всех пропущенных значений на 100",a)

# Проверка наличия NULL значений в массиве
print("Проверка наличия NULL значений в массиве\n",np.isnan(a).any())

# 2D массив

A = np.array([[1,2,np.nan,4] , [np.nan,6,7,8] , [9 , np.nan , 11 ,12] , [13,14,15,16]])
print("2D массив:\n", A)

# Поиск пропущенных значений и возврат их в виде булевого массива
print("Поиск пропущенных значений и возврат их в виде булевого массива\n",np.isnan(A))

# Индекс пропущенных значений в массиве
print("Индекс пропущенных значений в массиве\n", np.where(np.isnan(A)))

Пропущенные значения в массиве [ 3. nan  9.  5.  7. nan 11. inf]
Поиск пропущенных значений и возврат их в виде булевого массива [False  True False False False  True False False]
Индекс пропущенных значений в массиве (array([1, 5]),)
Замена всех пропущенных значений на 100 [  3. 100.   9.   5.   7. 100.  11.  inf]
Проверка наличия NULL значений в массиве
 False
2D массив:
 [[ 1.  2. nan  4.]
 [nan  6.  7.  8.]
 [ 9. nan 11. 12.]
 [13. 14. 15. 16.]]
Поиск пропущенных значений и возврат их в виде булевого массива
 [[False False  True False]
 [ True False False False]
 [False  True False False]
 [False False False False]]
Индекс пропущенных значений в массиве
 (array([0, 1, 2]), array([2, 0, 1]))


 <a name='join'></a>
Объединение массивов

In [20]:
# Создание массивов
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

# Вертикальное объединение массивов
vertical_stack = np.vstack((a,b,c))
print("Вертикальное объединение массивов:\n", vertical_stack)

# Горизонтальное объединение массивов
horizontal_stack = np.hstack((a,b,c))
print("Горизонтальное объединение массивов:\n", horizontal_stack)

Вертикальное объединение массивов:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Горизонтальное объединение массивов:
 [1 2 3 4 5 6 7 8 9]


 <a name='search'></a>
Поиск внутри массивов

In [21]:
# Создаем два массива
c1 = np.array([1,2,3,4,5,6])
c2 = np.array([12,2,33,4,55,6])

# Находим общие элементы между двумя массивами
common_items = np.intersect1d(c1,c2)
print("Общие элементы массивов:", common_items)

# Удаляем общие элементы из первого массива
c1_without_common = np.setdiff1d(c1,c2)
print("Первый массив без общих элементов:", c1_without_common)

Общие элементы массивов: [2 4 6]
Первый массив без общих элементов: [1 3 5]


 <a name='conds'></a>
Обработка элементов по условию

In [22]:
# Пример использования функции np.where для работы с условиями
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])

# Ищем индексы элементов, где условие a == b выполнено
print("Ищем индексы элементов, где условие a == b выполнено\n", np.where(a == b))

# Выводим элементы массива а, где условие a == b выполнено
print("Выводим элементы массива а, где условие a == b выполнено\n", a[np.where(a == b)])

# Создаем массив a1 от 0 до 59 и выводим все элементы, где условие (a1 > 20) & (a1 < 35) выполнено
a1 = np.arange(0,60)
a1[np.where ((a1>20) & (a1<35))]
print("Создаем массив a1 от 0 до 59 и выводим все элементы, где условие (a1 > 20) & (a1 < 35) выполнено\n", a1[np.where ((a1>20) & (a1<35))])

# Создаем массив a1 от 0 до 59 и выводим все элементы, где условие ((a1 > 20) & (a1 < 35)) | (a1 % 10 ==0) выполнено
a1 = np.arange(0,60)
a1[np.where (((a1>20) & (a1<35)) | (a1 % 10 ==0))]
print("Создаем массив a1 от 0 до 59 и выводим все элементы, где условие ((a1 > 20) & (a1 < 35)) | (a1 % 10 ==0) выполнено\n", a1[np.where (((a1>20) & (a1<35)) | (a1 % 10 ==0))])

# Создаем массив a1 от 0 до 59 и выводим все элементы, где условие (a1 > 20) & (a1 < 35) выполнено с помощью функции np.logical_and
a1[np.where(np.logical_and(a1>20, a1<35))]
print("Создаем массив a1 от 0 до 59 и выводим все элементы, где условие (a1 > 20) & (a1 < 35) выполнено с помощью функции np.logical_and\n",
     a1[np.where(np.logical_and(a1>20, a1<35))])

# Проверка наличия элементов в массиве с помощью функции np.isin()
a = np.array([10,20,30,40,50,60,70])
print("Массив a: ", a)

# Проверяем, есть ли числа 11 и 20 в массиве
print("Есть ли числа 11 и 20 в массиве a: ", np.isin(a, [11,20]))

# Выводим числа, которые совпали с 20
print("Числа из массива a, которые совпали с 20: ", a[np.isin(a,20)])

# Проверяем, есть ли число 33 в массиве
print("Есть ли число 33 в массиве a: ", np.isin(a, 33))

# Выводим число, которое совпало с 33 (если такое есть)
print("Число из массива a, которое совпало с 33: ", a[np.isin(a, 33)])

b = np.array([10,20,30,40,10,10,70,80,70,90])
print("Массив b: ", b)

# Проверяем, есть ли числа 10 и 70 в массиве
print("Есть ли числа 10 и 70 в массиве b: ", np.isin(b, [10,70]))

# Выводим индексы, где совпадение было найдено
print("Индексы элементов из массива b, которые совпали с числами 10 и 70: ", np.where(np.isin(b, [10,70])))

# Выводим значения, которые совпали с числами 10 и 70
print("Значения из массива b, которые совпали с числами 10 и 70: ", b[np.where(np.isin(b, [10,70]))])

# Альтернативный вариант вывода значений, которые совпали с числами 10 и 70
print("Значения из массива b, которые совпали с числами 10 и 70 (альтернативный вариант): ", b[np.isin(b, [10,70])])

Ищем индексы элементов, где условие a == b выполнено
 (array([1, 4]),)
Выводим элементы массива а, где условие a == b выполнено
 [2 8]
Создаем массив a1 от 0 до 59 и выводим все элементы, где условие (a1 > 20) & (a1 < 35) выполнено
 [21 22 23 24 25 26 27 28 29 30 31 32 33 34]
Создаем массив a1 от 0 до 59 и выводим все элементы, где условие ((a1 > 20) & (a1 < 35)) | (a1 % 10 ==0) выполнено
 [ 0 10 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 40 50]
Создаем массив a1 от 0 до 59 и выводим все элементы, где условие (a1 > 20) & (a1 < 35) выполнено с помощью функции np.logical_and
 [21 22 23 24 25 26 27 28 29 30 31 32 33 34]
Массив a:  [10 20 30 40 50 60 70]
Есть ли числа 11 и 20 в массиве a:  [False  True False False False False False]
Числа из массива a, которые совпали с 20:  [20]
Есть ли число 33 в массиве a:  [False False False False False False False]
Число из массива a, которое совпало с 33:  []
Массив b:  [10 20 30 40 10 10 70 80 70 90]
Есть ли числа 10 и 70 в массиве b:  [ True Fals

In [23]:
# Расчет количества вхождений каждого значния в массив
# Обратите внимание, что np.bincount работает только с неотрицательными целыми числами
arr = np.array([1, 1, 2, 3, 2, 1, 4])
print("Массив arr: ")
print(arr)

bincount_result = np.bincount(arr)
print("Количество вхождений каждого значения в массив arr с помощью np.bincount: ")
print(bincount_result)

Массив arr: 
[1 1 2 3 2 1 4]
Количество вхождений каждого значения в массив arr с помощью np.bincount: 
[0 3 2 1 1]


 <a name='sort'></a>
Cортировка массивов

In [24]:
# Обратный порядок массива
a4 = np.arange(0,30)
print("Исходный массив:", a4)
# Обратный порядок массива
print("Массив в обратном порядке:", a4[::-1])
# Обратный порядок массива
print("Массив в обратном порядке:", np.flip(a4))

a3 = np.array([[1,2,3,4] , [5,6,7,8] , [9,10,11,12] , [13,14,15,16]])
print("Исходный массив:")
print(a3)
# Обратный порядок строк
print("Массив со строками в обратном порядке:")
print(a3[::-1,])
# Обратный порядок столбцов
print("Массив со столбцами в обратном порядке:")
print(a3[:,::-1])
# Обратный порядок строк и столбцов
print("Массив со строками и столбцами в обратном порядке:")
print(a3[::-1,::-1])

Исходный массив: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Массив в обратном порядке: [29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]
Массив в обратном порядке: [29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]
Исходный массив:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Массив со строками в обратном порядке:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Массив со столбцами в обратном порядке:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
Массив со строками и столбцами в обратном порядке:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [25]:
# Сортировка массива
a = np.array([10,5,2,22,12,92,17,33])
# Сортировка по возрастанию
print("Массив в отсортированном порядке по возрастанию:")
print(np.sort(a))
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15]])
print("Исходный массив:")
print(a3)
# Сортировка строк по возрастанию
print("Массив со строками в отсортированном порядке по возрастанию:")
print(np.sort(a3))
# Сортировка строк по возрастанию
print("Массив со строками в отсортированном порядке по возрастанию:")
print(np.sort(a3,axis =1))
# Сортировка столбцов по возрастанию
print("Массив со столбцами в отсортированном порядке по возрастанию:")
print(np.sort(a3,axis =0))
# Сортировка по убыванию
b = np.sort(a)
b = b[::-1]
print("Массив в отсортированном порядке по убыванию:")
print(b)
# Сортировка по убыванию
c = np.sort(a)
print("Массив в отсортированном порядке по убыванию:")
print(np.flip(c))
# Сортировка по убыванию
a[::-1].sort()
print("Массив в отсортированном порядке по убыванию:")
print(a)

Массив в отсортированном порядке по возрастанию:
[ 2  5 10 12 17 22 33 92]
Исходный массив:
[[ 3  2  8  1]
 [70 50 10 67]
 [45 25 75 15]]
Массив со строками в отсортированном порядке по возрастанию:
[[ 1  2  3  8]
 [10 50 67 70]
 [15 25 45 75]]
Массив со строками в отсортированном порядке по возрастанию:
[[ 1  2  3  8]
 [10 50 67 70]
 [15 25 45 75]]
Массив со столбцами в отсортированном порядке по возрастанию:
[[ 3  2  8  1]
 [45 25 10 15]
 [70 50 75 67]]
Массив в отсортированном порядке по убыванию:
[92 33 22 17 12 10  5  2]
Массив в отсортированном порядке по убыванию:
[92 33 22 17 12 10  5  2]
Массив в отсортированном порядке по убыванию:
[92 33 22 17 12 10  5  2]


In [26]:
# # "N" наибольших и наименьших чисел в массиве
p = np.arange(0,50)
print("Массив p: ")
print(p)
np.random.shuffle(p)
print("Массив p после перемешивания: ")
print(p)

# Вернуть "n" наибольших чисел в массиве
n = 4
print("n наибольших чисел в массиве p: ")
print(p[np.argsort(p)[-n:]])
print(p[np.argpartition(-p,n)[:n]])

# Вернуть "n" наименьших чисел в массиве
print("n наименьших чисел в массиве p: ")
print(p[np.argsort(-p)[-n:]])
print(p[np.argpartition(p,n)[:n]])

Массив p: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Массив p после перемешивания: 
[16 12  3  1 43 26 49 47  4 31 37 27 40  9 29  8 38 45 44 11 33 14 36 19
 30 48 21 25 24 23  0 46 35 13 42 20 17  5 15  7  2  6 22 18 41 32 10 34
 39 28]
n наибольших чисел в массиве p: 
[46 47 48 49]
[48 49 47 46]
n наименьших чисел в массиве p: 
[3 2 1 0]
[1 0 2 3]


 <a name='compar'></a>
Сравнение массивов

In [27]:
# # Повторяющиеся последовательности
a5 = [10,20,30]
print("Массив a5: ")
print(a5)

# Повторить весь массив дважды
print("Массив a5, повторенный дважды: ")
print(np.tile(a5, 2))

# Повторить каждый элемент в массиве три раза
print("Каждый элемент массива a5, повторенный три раза: ")
print(np.repeat(a5, 3))

# # Сравнение массивов
d1 = np.arange(0,10)
print("Массив d1: ")
print(d1)

d2 = np.arange(0,10)
print("Массив d2: ")
print(d2)

d3 = np.arange(10,20)
print("Массив d3: ")
print(d3)

d4 = d1[::-1]
print("Массив d4: ")
print(d4)

# Сравнить массивы с помощью функции "allclose". Если эта функция возвращает True, то массивы равны
res1 = np.allclose(d1,d2)
print("Результат сравнения массивов d1 и d2: ")
print(res1)

# Сравнить массивы с помощью функции "allclose". Если эта функция возвращает False, то массивы не равны
res2 = np.allclose(d1,d3)
print("Результат сравнения массивов d1 и d3: ")
print(res2)

# Сравнить массивы с помощью функции "allclose"
res3 = np.allclose(d1,d4)
print("Результат сравнения массивов d1 и d4: ")
print(res3)

Массив a5: 
[10, 20, 30]
Массив a5, повторенный дважды: 
[10 20 30 10 20 30]
Каждый элемент массива a5, повторенный три раза: 
[10 10 10 20 20 20 30 30 30]
Массив d1: 
[0 1 2 3 4 5 6 7 8 9]
Массив d2: 
[0 1 2 3 4 5 6 7 8 9]
Массив d3: 
[10 11 12 13 14 15 16 17 18 19]
Массив d4: 
[9 8 7 6 5 4 3 2 1 0]
Результат сравнения массивов d1 и d2: 
True
Результат сравнения массивов d1 и d3: 
False
Результат сравнения массивов d1 и d4: 
False


 <a name='math'></a>
Математические операции

In [28]:
a = np.array([4,1,16])

# Деление массива на число
number = 2
divided = a / number
print(f"Массив a, делённый на {number}: ")
print(divided)

# Извлечение квадратного корня
print("Извлечение квадратного корня:")
square_root = np.sqrt(a)
print(square_root)

# Экспоненциальная функция
exp_values = np.exp(a)
print("Экспонента (e^x) для массива a: ")
print(exp_values)

# Натуральный логарифм (ln(x))
log_values = np.log(a)
print("Натуральный логарифм (ln(x)) для массива a: ")
print(log_values)

# Логарифм по основанию 2
log2_values = np.log2(a)
print("Логарифм по основанию 2 для массива a: ")
print(log2_values)

# Логарифм по основанию 10
log10_values = np.log10(a)
print("Логарифм по основанию 10 для массива a: ")
print(log10_values)

Массив a, делённый на 2: 
[2.  0.5 8. ]
Извлечение квадратного корня:
[2. 1. 4.]
Экспонента (e^x) для массива a: 
[5.45981500e+01 2.71828183e+00 8.88611052e+06]
Натуральный логарифм (ln(x)) для массива a: 
[1.38629436 0.         2.77258872]
Логарифм по основанию 2 для массива a: 
[2. 0. 4.]
Логарифм по основанию 10 для массива a: 
[0.60205999 0.         1.20411998]


 <a name='linalg'></a>
Функции линейной алгебры

In [29]:
# # Операции линейной алгебры
v1 = np.array([3, 4])
print("Вектор v1: ")
print(v1)

v2 = np.array([1, 2])
print("Вектор v2: ")
print(v2)

m1 = np.array([[1, 2], [3, 4]])
print("Матрица m1: ")
print(m1)

m2 = np.array([[2, 0], [1, 3]])
print("Матрица m2: ")
print(m2)

# Норма вектора
norm_v1 = np.linalg.norm(v1)
print("Норма вектора v1: ")
print(norm_v1)

# Скалярное произведение двух векторов
dot_product = np.dot(v1, v2)
print("Скалярное произведение векторов v1 и v2: ")
print(dot_product)

# Поэлементное умножение
print("Поэлементное произведение векторов v1 и v2: ")
elementwise_product = np.multiply(v1, v2)
print(elementwise_product)

# Внешнее векторное произведение
print("Внешнее произведение векторов v1 и v2: ")
outer = np.outer(v1, v2)
print(outer)

# Поэлементное умножение: умножаются соответствующие элементы векторов.
# Например, [1*4, 2*5, 3*6] = [4, 10, 18]

# Внешнее произведение: формируется матрица, где каждый элемент - это произведение всех возможных пар элементов из двух векторов.
# Например, для v1 = [1, 2, 3] и v2 = [4, 5, 6]:
# [
#   [1*4, 1*5, 1*6],
#   [2*4, 2*5, 2*6],
#   [3*4, 3*5, 3*6]
# ]

# Вычисление определителя матрицы
det_matrix = np.linalg.det(m1)
print("Определитель матрицы: ")
print(det_matrix)

# Умножение матриц
product = np.matmul(m1, m2)
print("Произведение матриц: ")
print(product)

# Вычисление обратной матрицы)
print("Обратная матрица для первой матрицы: ")
inverse_matrix = np.linalg.inv(m1)
print(inverse_matrix)

# Проверка умножения матрицы на её обратную (должен быть единичный массив)
identity_check = np.matmul(m1, inverse_matrix)
print("Результат умножения матрицы на её обратную: ")
print(identity_check)

Вектор v1: 
[3 4]
Вектор v2: 
[1 2]
Матрица m1: 
[[1 2]
 [3 4]]
Матрица m2: 
[[2 0]
 [1 3]]
Норма вектора v1: 
5.0
Скалярное произведение векторов v1 и v2: 
11
Поэлементное произведение векторов v1 и v2: 
[3 8]
Внешнее произведение векторов v1 и v2: 
[[3 6]
 [4 8]]
Определитель матрицы: 
-2.0000000000000004
Произведение матриц: 
[[ 4  6]
 [10 12]]
Обратная матрица для первой матрицы: 
[[-2.   1. ]
 [ 1.5 -0.5]]
Результат умножения матрицы на её обратную: 
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


[К оглавлению](#toc)

## Упражнение

Дан массив NumPy. Найти в нём максимальный элемент и заменить его на число 999.

Задача должна быть решена в NumPy синтаксисе, без циклов.

In [30]:
# Ваш код и комментарии
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])